### ISSUE TITLE
Ensure each of these issues are addressed in the whitepaper

### ISSUE THREAD

**Issue by JakeOShannessy** [Daolab/beaker-whitepaper#4]
The following issues have arisen which need clarification in the whitepaper.

- [ ] 1)  The paper is not very accessible to a wider technical audience.
- [x] 2)  What is the exact problem that BeakerOS solves?
- [x] 3)  What is the intended scope/granularity of BeakerOS' access-control?
- [x] 4)  Why is the problem that BeakerOS addresses relevant?
- [x] 5)  Why is the proposed solution, namely an exokernel, adequate?
- [x] 6)  Are there existing use cases where BeakerOS is adequate?
- [ ] 7)  Do BeakerOS' promises correspond to reality?

**Comment by JakeOShannessy** [comment]
Issue no. 1 is a little subjective, but I've tried to make improvements where I can. I think we already address no. 3 sufficiently.

No. 7 might still be something to think about.

These are all being worked on in #7.

**Comment by Latrasis** [comment]
@JakeOShannessy: I agree that no.3 is already addressed.

I don't think no.1 is our goal, and i believe no.7 can only be addressed by implementation and real-world use.

**Comment by Latrasis** [comment]
Closing this since #7
