### ISSUE TITLE
Address Procedure Registration

### ISSUE THREAD

**Issue by Latrasis** [Daolab/beaker-whitepaper#6]
We need to replace procedure creation with procedure registration

**Comment by JakeOShannessy** [comment]
@Latrasis  the text has been updated, but the diagram needs to be updated too. You might be the best placed to do that.

**Comment by Latrasis** [comment]
Great! Will do. We might want to update the heading to Procedure Registration to fit it better.

**Comment by JakeOShannessy** [comment]
The heading has been updated

**Comment by JakeOShannessy** [comment]
See PR #7

**Comment by Latrasis** [comment]
Addressedin #7
